jobs:
  allow_failures:
    - arch: arm64
  fast_finish: true
  include:
    - name: "Linux ARM64v8 (Debian 12, glibc 2.36) - .NET 8.0"
      arch: arm64
      os: linux
      dist: focal
      language: shell
      install:
        - sudo docker run -dit --name netvips -e TRAVIS -v $(pwd):/mnt/netvips -w /mnt/netvips mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim-arm64v8
        - sudo docker exec netvips sh -c "apt-get update && apt-get install -y fontconfig-config"
      script: sudo docker exec netvips bash -c "./build.sh"
    - name: "Linux ARM64v8 (Alpine 3.18, musl 1.2.4) - .NET 8.0"
      arch: arm64
      os: linux
      dist: focal
      language: shell
      install:
        - sudo docker run -dit --name netvips -e TRAVIS -v $(pwd):/mnt/netvips -w /mnt/netvips mcr.microsoft.com/dotnet/sdk:8.0-alpine3.18-arm64v8
        - sudo docker exec netvips sh -c "apk add bash font-noto --update-cache"
      script: sudo docker exec netvips bash -c "./build.sh"
