image: Visual Studio 2022

# Version format
version: 3.0.0.{build}

init:
  - git config --global core.autocrlf true

# Environment
environment:
  VIPS_VERSION: "8.16.0"
  VIPS_WARNING: 0

# https://github.com/appveyor/ci/issues/3936
install:
  - ps: |
      Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
      & $env:temp\dotnet-install.ps1 -Architecture x64 -Channel 9.0 -InstallDir "$env:ProgramFiles\dotnet"

# Build script
build_script:
  - ps: .\build.ps1 --package

# Do not build on tags (GitHub only)
skip_tags: true

pull_requests:
  do_not_increment_build_number: true

# Disable automatic tests and deployment
test: off
deploy: off

# Branches to build
branches:
  # Blocklist
  except:
    - gh-pages

# Build cache
cache:
  - download -> appveyor.yml, build\Build.cs

artifacts:
  - path: '**\NetVips.*.nupkg' # find all NuGet packages recursively
