name: CI
on: [ push, pull_request ]
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            container: mcr.microsoft.com/dotnet/sdk:7.0-bullseye-slim
            script: ./build.sh
          - os: ubuntu-22.04
            container: centos:7
            script: ./build.sh
          - os: ubuntu-22.04
            container: mcr.microsoft.com/dotnet/sdk:7.0-alpine3.16
            script: ./build.sh
          # TODO(kleisauke): Re-enable Mono CI when C# 9 features are supported.
          # - os: ubuntu-22.04
          #   script: ./build/test-mono.sh
          #   allow_failures: true
          - os: macos-12
            script: ./build.sh
          - os: windows-2022
            script: .\build.ps1
    steps:
      - name: Dependencies (Debian 11)
        if: contains(matrix.container, 'bullseye')
        run: |
          apt-get update
          apt-get install -y fontconfig-config
      - name: Dependencies (CentOS 7)
        if: contains(matrix.container, 'centos')
        run: |
          yum install -y \
            https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
          yum install -y dotnet-sdk-7.0 google-noto-sans-fonts which
      - name: Dependencies (Alpine 3.16)
        if: contains(matrix.container, 'alpine')
        run: apk add bash font-noto --update-cache
      - name: Setup dotnet (macOS 12, Windows 2022)
        if: runner.os != 'Linux'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        continue-on-error: ${{ matrix.allow_failures == true }}
        run: ${{ matrix.script }}
